# Generated by Django 5.0.13 on 2025-06-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCluster',
            fields=[
                ('cluster_id', models.CharField(help_text='ID duy nhất của cụm địa chỉ', max_length=64, primary_key=True, serialize=False)),
                ('address_count', models.PositiveIntegerField(default=1, help_text='Số lượng địa chỉ trong cụm')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo cụm')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cụm')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú về cụm (ví dụ: sàn giao dịch, ví cá nhân)', null=True)),
            ],
            options={
                'verbose_name': 'Cụm Địa chỉ',
                'verbose_name_plural': 'Các cụm Địa chỉ',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('hash', models.CharField(help_text='Mã hash của khối', max_length=64, primary_key=True, serialize=False)),
                ('height', models.PositiveIntegerField(db_index=True, help_text='Chiều cao của khối', unique=True)),
                ('time', models.DateTimeField(db_index=True, help_text='Thời gian khối được tạo (UTC)')),
                ('n_tx', models.PositiveIntegerField(help_text='Số lượng giao dịch trong khối')),
                ('fee', models.PositiveBigIntegerField(help_text='Tổng phí giao dịch trong khối (satoshi)')),
            ],
            options={
                'verbose_name': 'Khối',
                'verbose_name_plural': 'Các khối',
                'ordering': ['-height'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(help_text='Địa chỉ Bitcoin', max_length=128, primary_key=True, serialize=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='Lần đầu tiên địa chỉ xuất hiện')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Lần cuối địa chỉ xuất hiện')),
                ('is_exchange', models.BooleanField(db_index=True, default=False, help_text='Là địa chỉ sàn giao dịch?')),
                ('tags', models.CharField(blank=True, db_index=True, help_text="Nhãn đánh dấu (ví dụ: 'scam', 'mixing', 'whale')", max_length=100, null=True)),
                ('tx_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Số lượng giao dịch liên quan')),
                ('cluster', models.ForeignKey(blank=True, help_text='Cụm địa chỉ mà địa chỉ này thuộc về', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='bitcoin.addresscluster')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Các địa chỉ',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('hash', models.CharField(help_text='Mã hash (TxID) của giao dịch', max_length=64, primary_key=True, serialize=False)),
                ('tx_index', models.PositiveBigIntegerField(db_index=True, help_text='Chỉ số giao dịch (từ Blockchain.com API)', unique=True)),
                ('time', models.DateTimeField(db_index=True, help_text='Thời gian giao dịch (UTC)')),
                ('fee', models.PositiveBigIntegerField(help_text='Phí giao dịch (satoshi)')),
                ('vin_sz', models.PositiveSmallIntegerField(help_text='Số lượng đầu vào')),
                ('vout_sz', models.PositiveSmallIntegerField(help_text='Số lượng đầu ra')),
                ('size', models.PositiveIntegerField(help_text='Kích thước giao dịch (bytes)')),
                ('weight', models.PositiveIntegerField(help_text='Trọng lượng giao dịch (WU)')),
                ('lock_time', models.PositiveIntegerField(help_text='Lock time của giao dịch')),
                ('is_coinbase', models.BooleanField(default=False, help_text='Là giao dịch coinbase?')),
                ('anomaly_score', models.FloatField(db_index=True, default=0.0, help_text='Điểm bất thường (tính toán sau)')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú phân tích', null=True)),
                ('total_output_value', models.PositiveBigIntegerField(default=0, help_text='Tổng giá trị đầu ra (satoshi)')),
                ('tags', models.CharField(blank=True, db_index=True, help_text='Các nhãn (phân tách bởi dấu phẩy, ví dụ: large_value, high_fee, mixing, peeling)', max_length=255, null=True)),
                ('block', models.ForeignKey(help_text='Khối chứa giao dịch', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bitcoin.block')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Các giao dịch',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='TxInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_index', models.PositiveSmallIntegerField(help_text='Thứ tự của đầu vào trong giao dịch')),
                ('prev_tx_hash', models.CharField(blank=True, db_index=True, help_text='Hash của giao dịch trước (null nếu coinbase)', max_length=64, null=True)),
                ('prev_output_index', models.PositiveIntegerField(blank=True, help_text='Chỉ số đầu ra của giao dịch trước (null nếu coinbase)', null=True)),
                ('prev_value', models.PositiveBigIntegerField(blank=True, help_text='Giá trị của UTXO được chi tiêu', null=True)),
                ('sequence', models.BigIntegerField()),
                ('address', models.ForeignKey(help_text='Địa chỉ sở hữu UTXO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spent_txos', to='bitcoin.address')),
                ('transaction', models.ForeignKey(help_text='Giao dịch chứa đầu vào này', on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='bitcoin.transaction')),
            ],
            options={
                'verbose_name': 'Đầu vào Giao dịch',
                'verbose_name_plural': 'Các đầu vào Giao dịch',
                'ordering': ['transaction', 'input_index'],
            },
        ),
        migrations.CreateModel(
            name='TxOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output_index', models.PositiveSmallIntegerField(help_text='Thứ tự của đầu ra trong giao dịch')),
                ('value', models.PositiveBigIntegerField(help_text='Giá trị của đầu ra (satoshi)')),
                ('script_pub_key', models.TextField(help_text='Script khóa (scriptPubKey)')),
                ('is_spent', models.BooleanField(db_index=True, default=False, help_text='Đầu ra này đã được chi tiêu chưa?')),
                ('spending_tx_hash', models.CharField(blank=True, db_index=True, help_text='Hash của giao dịch chi tiêu đầu ra này', max_length=64, null=True)),
                ('spending_input_index', models.PositiveSmallIntegerField(blank=True, help_text='Chỉ số đầu vào chi tiêu đầu ra này', null=True)),
                ('address', models.ForeignKey(help_text='Địa chỉ nhận đầu ra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_txos', to='bitcoin.address')),
                ('transaction', models.ForeignKey(help_text='Giao dịch tạo ra đầu ra này', on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='bitcoin.transaction')),
            ],
            options={
                'verbose_name': 'Đầu ra Giao dịch (UTXO)',
                'verbose_name_plural': 'Các đầu ra Giao dịch (UTXOs)',
                'ordering': ['transaction', 'output_index'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_index', 'hash'], name='bitcoin_tra_tx_inde_73d7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='txinput',
            index=models.Index(fields=['prev_tx_hash', 'prev_output_index'], name='bitcoin_txi_prev_tx_3a0a6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='txinput',
            unique_together={('transaction', 'input_index')},
        ),
        migrations.AddIndex(
            model_name='txoutput',
            index=models.Index(fields=['transaction', 'output_index'], name='bitcoin_txo_transac_7fbcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='txoutput',
            index=models.Index(fields=['address', 'is_spent'], name='bitcoin_txo_address_9ee3c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='txoutput',
            unique_together={('transaction', 'output_index')},
        ),
    ]
